version: '3.7'

services:
    api:
        environment: 
            MONGO_USERNAME: niconiconii
            MONGO_PASS: にっこにっこにー
            MONGO_HOST: localhost
            MONGO_DB: testingdb
            PORT: 4327
	    volumes:
            - ./services/api:/usr/app
            - /usr/app/node_modules/
    frontend:
        environment: 
            API_URL: localhost:4327/api
            PORT: 4328
	    volumes:
            - ./services/frontend:/usr/app
            - /usr/app/node_modules/
    mongo:
        environment: 
            MONGO_INITDB_ROOT_USERNAME: niconiconii
            MONGO_INITDB_ROOT_PASSWORD: にっこにっこにー