version: '3.7'

services:
    api:
        build:
            context: .
            dockerfile: ./services/api/Dockerfile.local
        environment: 
            MONGO_URI: mongodb://niconiconii:thisisatest@mongoodatabase:27017/db
            JWT_KEY: thisisatestkey
            PORT: 4327
        ports:
            - "4327:4327"
        volumes:
            - ./services/api:/usr/app/services/api
        networks:
            - main-network
    frontend:
        build:
            context: .
            dockerfile: ./services/frontend/Dockerfile.local
        environment: 
            API_URL: localhost:4327/api
            WS_URL: localhost:4329/ws
            PORT: 4328
        ports:
            - "4328:4328"
        volumes:
            - ./services/frontend:/usr/app/services/frontend
    ws:
        build:
            context: .
            dockerfile: ./services/ws/Dockerfile.local
        environment: 
            MONGO_URI: mongodb://niconiconii:thisisatest@mongoodatabase:27017/db
            PORT: 4329
        ports:
            - "4329:4329"
        volumes:
            - ./services/ws:/usr/app/services/ws
        networks:
            - main-network
    mongodatabase:
        ports:
            - "27017:27017"
        environment: 
            MONGO_INITDB_ROOT_USERNAME: niconiconii
            MONGO_INITDB_ROOT_PASSWORD: thisisatest
            MONGO_INITDB_DATABASE: testing
        networks:
            - main-network
networks:
    main-network:
        driver: bridge
