version: '3.7'

services:
  api:
    container_name: FLOURS_API
    restart: unless-stopped
    ports:
      - "${PORT}:${PORT}"
    depends_on: 
      - mongo
  frontend:
    container_name: FLOURS_FRONTEND
    restart: unless-stopped
    ports:
      - "${PORT}:${PORT}"
    depends_on: 
      - api
  mongo:
    container_name: FLOURS_MONGO_DB
    image: mongo
    restart: unless-stopped