version: '3.7'

services:
  api:
    container_name: FLOURS_API
    restart: unless-stopped
    depends_on: 
      - mongodatabase
  frontend:
    container_name: FLOURS_FRONTEND
    restart: unless-stopped
    depends_on: 
      - api
  ws:
    container_name: FLOURS_WS
    restart: unless-stopped
    depends_on: 
      - mongodatabase
  mongodatabase:
    container_name: FLOURS_MONGO_DB
    image: mongo
    restart: unless-stopped
    volumes: 
      - ./volumes/db/mongo:/data/db