version: '3.7'

services:
  api:
    env_file: .env
    ports:
      - "${PORT}:${PORT}"
  ws:
    env_file: .env
    ports:
      - "${PORT}:${PORT}"
  mongo:
    env_file: .env
    ports:
      - "${PORT}:${PORT}"